server:
  port: 8080
  address: 0.0.0.0

spring.application.name: sp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rainwaterDB?useSSL=false&serverTimezone=UTC
    username: postgres
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource

mybatis:
  mapper-locations: classpath*:uk/ac/bristol/dao/*.xml
  type-aliases-package: uk.ac.bristol.pojo

mock-data:
  assets: src/main/resources/data/assets.json
  asset-types: src/main/resources/data/asset_types.json
  users: src/main/resources/data/users.json
  warnings: src/main/resources/data/arcgis-sample.json
  js: src/main/resources/js/arcgis-converter.js
  state: src/main/resources/data/mock_data_state.json

logging:
  level:
    uk.ac.bristol.dao: DEBUG
    org.apache.ibatis: DEBUG