server:
  port: 8080
  address: 0.0.0.0

spring.application.name: sp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/rainwaterDB?useSSL=false&serverTimezone=UTC
    username: postgres
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:uk/ac/bristol/dao/*.xml
  type-aliases-package: uk.ac.bristol.pojo


logging:
  level:
    uk.ac.bristol.dao: DEBUG
    org.apache.ibatis: DEBUG
    org.mybatis: DEBUG