server:
  port: 8080
  address: 0.0.0.0

spring.application.name: sp

app:
  base-url: https://sp.zr17.fun
  http-only: true
  pagination-limit: 1000
  pagination-max-page: 50

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/rainwaterDB?useSSL=false&serverTimezone=UTC
    username: postgres
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource

  mail:
    username: alchemistbackydian@gmail.com
    password: ijllbowymtlavkvx
    host: smtp.gmail.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
            fallback: false

  redis:
    host: redis
    port: 6379

mybatis:
  mapper-locations: classpath*:uk/ac/bristol/dao/*.xml
  type-aliases-package: uk.ac.bristol.pojo

mock-data:
  assets: data/assets.json
  asset-types: data/asset_types.json
  users: data/users.json
  warnings: data/geojson-sample.json
  notifications: data/templates.json
  state: mock-data-state/mock_data_state.json

metoffice:
  url:  "https://services.arcgis.com/Lq3V5RFuTBC9I7kv/arcgis/rest/services/Met_Office_National_Severe_Weather_Warning_Service_Live/FeatureServer/0/query?where=1=1&outFields=*&returnGeometry=true&f=pgeojson"
  crawler:
    rate: 600000

logging:
  level:
    uk.ac.bristol.dao: DEBUG
    org.apache.ibatis: DEBUG
    org:
      springframework:
        mail: DEBUG
        boot:
          autoconfigure:
            mail: DEBUG

twilio:
  account-sid: ACca414e42cf744fe7c04c1bef9c0d09c3
  auth-token: 94c438edc8444eae48d0be61a44eadab
  from-number: "+447473357602"