server:
  port: 8080
  address: 0.0.0.0

spring.application.name: sp

app:
  base-url: https://sp.zr17.fun

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/rainwaterDB?useSSL=false&serverTimezone=UTC
    username: postgres
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource

  mail:
    username: alchemistbackydian@gmail.com
    password: ijllbowymtlavkvx
    host: smtp.gmail.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
            fallback: false

mybatis:
  mapper-locations: classpath*:uk/ac/bristol/dao/*.xml
  type-aliases-package: uk.ac.bristol.pojo

mock-data:
  assets: data/assets.json
  asset-types: data/asset_types.json
  users: data/users.json
  warnings: data/geojson-sample.json
  notifications: data/notifications.json
  state: mock-data-state/mock_data_state.json

metoffice:
  url:  "https://services.arcgis.com/Lq3V5RFuTBC9I7kv/arcgis/rest/services/Met_Office_National_Severe_Weather_Warning_Service_Live/FeatureServer/0/query?where=1=1&outFields=*&returnGeometry=true&f=pgeojson"
  crawler:
    rate: 600000

logging:
  level:
    uk.ac.bristol.dao: DEBUG
    org.apache.ibatis: DEBUG