version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - backend

  db:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_DB: rainwaterDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      JWT_SECRET_KEY: testSecretKeyJWTWhichMustBeLongerThan32CharactersToSatisfyTheHS256Algorithm
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
