spring.application.name=mail

*??*
spring.mail.properties.mail.smtp.auth=true

*???????*
spring.mail.username=alchemistbackydian@gmail.com

*?????????*
spring.mail.password=ijllbowymtlavkvx

*??smtp?????????gmail???465?SSL?*
spring.mail.host=smtp.gmail.com
spring.mail.port=465

*?????????????*
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.fallback=false

*??debug??*
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.boot.autoconfigure.mail=DEBUG

*database*
spring.datasource.url=jdbc:postgresql://localhost:5432/mail?useSSL=false&serverTimezone=UTC
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=org.example.mail.dao

*twilio_account_info*
twilio.accountSid=AC6201dd317e7b507897936f16df4306fa
twilio.authToken=8d8103ff7c4ad8d3ee90cf5f585ba7b4
*free_number_no_adjustment*
twilio.whatsappFrom=whatsapp:+14155238886