/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElLoading: typeof import('element-plus')['ElLoading']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElMessage2: typeof import('element-plus/es')['ElMessage2']
  const ElMessageBox: typeof import('element-plus')['ElMessageBox']
  const ElMessageMock: typeof import('element-plus/es')['ElMessageMock']
}
